name: Compile & Test

on:
  pull_request:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-cache
      - name: Compile and Check Formatting
        run: sbt downloadBitcoind downloadLnd test:compile scalafmtCheckAll test

  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-cache
      - name: Compile
        run: sbt test:compile

  windows:
    runs-on: windows-latest
    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-cache
      - name: Compile
        run: sbt test:compile
