name: Compile & Test

on:
  pull_request:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Java 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "11"
          cache: sbt
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Compile and Check Formatting
        run: sbt -Dsbt.supershell=false downloadBitcoind downloadLnd test:compile scalafmtCheckAll test

  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build Nix package
        run: nix build .#default --no-link
